### ISSUE TITLE
HIGH PRIORITY > Copyright in footer requires year

### ISSUE THREAD

**Issue by lindsey-rix** [blackbaud-community/stache#111]
SKY API team is working on adding legal terms of use to site for the SKY API GA. Legal has informed us that in order for the copyright to be legally binding, the year must be included. The year needs to be the first year of its publication. So, they want 2016 in the footer for this part:
© Blackbaud, Inc. All rights reserved.

Legal is asking for it to be right-aligned as welll.

Details can be found in this user story: https://tfs.blackbaud.com/tfs/DefaultCollection/Products/_workitems?_a=edit&id=527867

Contact for the work: Adam Hickey on the A-Team.

**Comment by blackbaud-brandonhare** [comment]
Resolved
