### ISSUE TITLE
Skyux tutorial 

### ISSUE THREAD

**Issue by wmaszk** [blackbaud-community/stache#145]
https://host.nxt.blackbaud.com/learn-skyux/tutorials/project-setup/enable-auth-omnibar

if you place it on half screen view and scroll down the drop down menu goes over top of the words

**Comment by Blackbaud-BrandonJones** [comment]
Hey! Thank you for reporting this issue, can we get a little more information or screen shots?  what browser are you using? What OS? Thank you again :)

**Comment by Blackbaud-BrandonJones** [comment]
Also this appears to be a tutorial written in Stache 2.  With more information we can move the issue to the Stache2 repo.
https://github.com/blackbaud/stache2/issues

**Comment by Blackbaud-BrandonJones** [comment]
Hey!  Thanks for taking the time to bring an issue to our attention. We would love to work on resolving this. First this issue should be  should be filed in the Stache 2 repo found here, this Stache repo is for Stache (1) issues, and is being deprecated.

https://github.com/blackbaud/stache2/issues

Second, can you provide any more details for this issue? Screen shots of the behavior, OS you are running, and browser you experienced this issue.  That will help us find and reproduce the bug so we can fix it.  Thank you again!

Issue was moved here:
https://github.com/blackbaud/stache2/issues/467
