### ISSUE TITLE
Affixed sidebar overlaps breadcrumbs

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud-community/stache#30]
Enable breadcrumbs and use the sidebar layout.  Notice that the sidebar will overlap the breadcrumbs text.

**Comment by Blackbaud-SteveBrush** [comment]
This [pull request](https://github.com/blackbaud/stache/pull/41) should fix the overlap issue.

**Comment by Blackbaud-BobbyEarl** [comment]
Fixed in the PR Steve mentioned.
