### ISSUE TITLE
Update FontAwesome library

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud-community/stache#31]
Icons in the 4.5 FontAwesome set cannot be used in a Stache site.

**Comment by Blackbaud-BobbyEarl** [comment]
Progress #32

**Comment by Blackbaud-BobbyEarl** [comment]
Upgraded the version of SKY UX, which included FontAwesome 4.5.0.  Need Stache version 0.7.9 or later.  Thanks for the heads up!
