### ISSUE TITLE
Use Open API Specification to generate a technical reference

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud-community/stache#43]
**Implementing [Open API](https://github.com/OAI/OpenAPI-Specification) (formerly [swagger.io](http://swagger.io/)):**
- How much (if any) can we leverage the [existing swagger tools](http://swagger.io/tools/) for docs and code sample creation? Do we have to reinvent the wheel?
- Goal: Given an Open API Spec for a REST API, provide the ability to auto-generate a technical reference into a Stache website.

**Comment by Blackbaud-SteveBrush** [comment]
Azure APIM will allow you to import WADL or Swagger

**Comment by blackbaud-brandonhare** [comment]
This is now in Stache as of version 0.7.20.
