### ISSUE TITLE
preStache hooks don't run during watch task

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud-community/stache#48]
Steps to duplicate
- Create a Stache project and specify `preStache` hooks in your gruntfile.
- Run `stache serve`.  Your `preStache` hook will run.
- Change a source file to trigger the  watch task.  The `preStache` hook will not run.

**Comment by Blackbaud-BobbyEarl** [comment]
Added via https://github.com/blackbaud/stache/pull/50
