### ISSUE TITLE
New stache site does not use latest deploy method

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud-community/stache#58]
When you create a stache site using `stache new my-site`, the deployment method is not updated.

`deploy.sh` should be removed from the template.

The `.deployment` file should have the following change:
Old: `command = bash deploy.sh`
New: `command = npm install -g blackbaud-stache-cli && stache deploy --no-color`

**Comment by Blackbaud-BobbyEarl** [comment]
In Stache CLI version 0.3.11.
