### ISSUE TITLE
Stache template links to defunct azure sample site

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud-community/stache#59]
When you create a new stache site using `stache new my-site`, some sample content is added.

The Showcase Pattern page says "Check out Stache Docs for a comprehensive look at all our navigation patterns", and links to http://blackbaud-stache.azurewebsites.net/patterns/. This site is unavailable. It should link to http://stache.docs.blackbaudhosting.com/patterns/.

There may be other links in the template that go to the wrong place.

**Comment by Blackbaud-ChristiSchneider** [comment]
Actually the stache docs site is internal - I thought it was publicly visible, so that may not be the correct site.

**Comment by Blackbaud-BobbyEarl** [comment]
In Stache CLI version 0.3.11.
