### ISSUE TITLE
Make layout-panels equal heights by default, deprecate layout-panels-equal.

### ISSUE THREAD

**Issue by blackbaud-brandonhare** [blackbaud-community/stache#71]
Currently, layout-panels uses jQuery to dynamically set the height of each element to that of the highest one in the row, whereas layout-panels-equal uses a hard coded height value. We should make the equal height option the default behavior of layout-panels and deprecate the layout-panels-equal layout.

**Comment by Blackbaud-SteveBrush** [comment]
Done. #77
