### ISSUE TITLE
Customize site base path

### ISSUE THREAD

**Issue by mbuhot** [blackbaud-community/stache#94]
I'd like to host a stache site within another web application (everydayhero.com apis) at the `/doc` path.

eg:

`/doc/index.html` will be the stache site home page.
`/doc/getting-started.html`, `/doc/api-reference.html`, etc. will be the content pages.

However the navigation links use a path expecting the stache site to be at `/`.

Can I customize the links to include a base path?

**Comment by mbuhot** [comment]
Looks like 

``` yaml
base: /doc/
```

in stache.yml does the trick

**Comment by mbuhot** [comment]
Maybe this should be documented in  http://stache.docs.blackbaudhosting.com/resources/built_in_yaml_variables/navigation/ ?

I can send a PR, but not sure where the source for that site is :)

**Comment by Blackbaud-BobbyEarl** [comment]
Glad you were able to find what you needed @mbuhot.  Currently the source repo for the documentation exists in the [blackbaud-community](https://github.com/blackbaud/stache-docs) organization.  I've added you as a reader.  If you're comfortable filing a PR, that would be great.

Let us know if there's anything else we can do to help!

**Comment by mbuhot** [comment]
@Blackbaud-BobbyEarl I get a 404 on that link.
I couldn't see stache-docs on https://github.com/blackbaud-community either.

**Comment by mbuhot** [comment]
OK, got the blackbaud org invite, thanks @Blackbaud-BobbyEarl 👍
